### ISSUE TITLE
DMG file no longer available

### ISSUE THREAD

**Issue by JamesBissick** [jariz/XDiscord#7]
Title says it all.

**Comment by ghost** [comment]
Yup, was looking forward to this but the file is not available.

**Comment by jariz** [comment]
The app works, but I still wanted to add a preferences screen and some onboarding stuff before I deemed it done... and then I lost interest in the project.
I'll try to get a build up today, don't know if I'll ever finish this but seems like a waste to not have it be usable at all.

**Comment by JamesBissick** [comment]
>  still wanted to add a preferences screen and some onboarding stuff before I deemed it done... and then I lost interest in the project

I thought that was the case.. Your project is great and it's the only application that does what it does so far.

**Comment by charliekmcmahon** [comment]
@jariz Sorry to bother you, however, I think this app would be really awesome to have released, even in a very early beta stage. Would it be possible for you to give us access to the older version dmg even if you haven't got the new one ready yet? Thanks and no worries if not

**Comment by qyzdo** [comment]
I'm waiting too! Hope it will be released soon :)

**Comment by pandafliesinspace** [comment]
Also interested

**Comment by sunsetsonwheels** [comment]
Same here, bumping this issue :)

**Comment by Yaboi-solo** [comment]
Yes please, that would be nice.

**Comment by SteveGremory** [comment]
It Would Be amazing indeed.

**Comment by aheze** [comment]
If anyone wants a zip of the compiled app, here it is (for Intel):

[XDiscord.zip](https://github.com/jariz/XDiscord/files/5758347/XDiscord.zip)

And here's one for M1 (Apple Silicon):

[XDiscord 2.zip](https://github.com/jariz/XDiscord/files/5758356/XDiscord.2.zip)

**Comment by nayred3** [comment]
> If anyone wants a zip, here it is (for Intel):
> 
> [XDiscord.zip](https://github.com/jariz/XDiscord/files/5758347/XDiscord.zip)
> 
> And here's one for M1 (Apple Silicon):
> 
> [XDiscord 2.zip](https://github.com/jariz/XDiscord/files/5758356/XDiscord.2.zip)

RIP I can't open the application because it can't be checked for malicious software

**Comment by aheze** [comment]
@nayred3 hmm, that is weird. You can press the arrow and then <kbd>Keep</kbd> for now:

![Screen Shot 2021-02-04 at 3 30 05 PM](https://user-images.githubusercontent.com/49819455/106968574-fd751580-66fd-11eb-980b-fe5cb7269c7e.png)

**Comment by aheze** [comment]
https://user-images.githubusercontent.com/49819455/106969039-f1d61e80-66fe-11eb-9303-9e763738f00d.mov

**Comment by JamesBissick** [comment]
Still no DMG besides aheze's. I'm closing this issue.
